### ISSUE TITLE
common/lib"' has no exported member 'RouteService'

### ISSUE THREAD

**Issue by classicCokie** [TypedProject/tsed-example-session#1]
Hey there,

when I do a fresh git clone of this repo, stay on the master branch and then do a yarn install and try to start the project with yarn start I get the following error:

![image](https://user-images.githubusercontent.com/10669108/102694773-7c33f300-4223-11eb-9ad4-fb0c985544b3.png)

Seems like there has been a change in the exported members?

**Comment by Romakita** [comment]
Hello @classicCokie 
I haven’t updated this project since the v6 have been released. Just remove the RouteService ;)

see you
Romain

**Comment by classicCokie** [comment]
ah got it! Thanks for the quick answer
